#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../autoload.php';

use Wpkit\Command\PluginCreateCommand;
use Wpkit\Command\NamespaceUpdateCommand;
use Symfony\Component\Console\Application;
use Wpkit\Command\RouteCreateCommand;

$application = new Application();
$application->add(new PluginCreateCommand());
$application->add(new NamespaceUpdateCommand());
$application->add(new RouteCreateCommand());
$application->run();
