#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Wpkit\Command\LintCheckCommand;
use Wpkit\Command\AiCheckCommand;
use Wpkit\Command\AiDiffCommand;
use Wpkit\Command\AiFindCommand;
use Wpkit\Command\AiIndexBuildCommand;
use Wpkit\Command\AiIndexRemoveCommand;
use Wpkit\Command\AiIndexShowCommand;
use Wpkit\Command\AiIndexUpdateCommand;
use Wpkit\Command\AiReadCommand;
use Wpkit\Command\AiStatusCommand;
use Wpkit\Command\AiWriteCommand;
use Wpkit\Command\RouteCreateCommand;
use Wpkit\Command\ScaffoldMakeCommand;
use Wpkit\Command\PluginCreateCommand;
use Wpkit\Command\ProjectBuildCommand;
use Wpkit\Command\NamespaceUpdateCommand;
use Symfony\Component\Console\Application;
use Wpkit\Command\PluginInitConfigCommand;
use Wpkit\Command\PluginCreateFromFileCommand;
use Wpkit\Controller\ScaffoldCatalog;

$application = new Application();
$application->add(new AiCheckCommand());
$application->add(new AiDiffCommand());
$application->add(new AiFindCommand());
$application->add(new AiIndexBuildCommand());
$application->add(new AiIndexRemoveCommand());
$application->add(new AiIndexShowCommand());
$application->add(new AiIndexUpdateCommand());
$application->add(new AiReadCommand());
$application->add(new AiStatusCommand());
$application->add(new AiWriteCommand());
$application->add(new PluginCreateCommand());
$application->add(new NamespaceUpdateCommand());
$application->add(new RouteCreateCommand());
$application->add(new PluginCreateFromFileCommand());
$application->add(new PluginInitConfigCommand());
$application->add(new LintCheckCommand());
$application->add(new ProjectBuildCommand());

foreach (ScaffoldCatalog::makeDefinitions() as $definition) {
    $application->add(new ScaffoldMakeCommand($definition));
}

$application->run();
